### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by mjackson** [algolia/expect-to-equal-jsx#1]
Would you be open to renaming the project from `expect-to-equal-jsx` to simply `expect-jsx`? I think the name is a bit stronger, and would help people understand better what it's for.

**Comment by vvo** [comment]
Ah yes good, will do.

What about the underlying `react-element-to-jsx-string`, have a better name or we are good?

**Comment by vvo** [comment]
Also, would we keep `toEqualJSX`? I believe yes.

**Comment by vvo** [comment]
On moved in #3
